#!/usr/bin/env python3
"""Reproduce the pinned Harmony per-channel INT8 Community encoder.

Calibration tensors are private derived features, not repository assets. This
tool binds their aggregate digest, the FP32 source, dependency versions and the
generated bytes so a different calibration set cannot silently become a release
model.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import re
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "shared/models/asr/dingqiao/community-wespeaker-encoder.fp32.onnx"
EXPECTED_SOURCE_SHA256 = "8f8c4619237d023770f5ed18012123771e216c5ec358987b8d3c4e486a74d30f"
EXPECTED_CALIBRATION_DIGEST = "a7f365b413beb8fa1cc767c78133f705f8812c466f1876156c59178a34235e1a"
EXPECTED_CALIBRATION_WINDOWS = 21
EXPECTED_OUTPUT_SHA256 = "368629e9bad8277b5249b70eec1879bf293e1be614569c3257fdea937211eedd"
EXPECTED_OUTPUT_BYTES = 5_468_354
EXPECTED_VERSIONS = {
    "numpy": "1.26.4",
    "onnx": "1.15.0",
    "onnxruntime": "1.16.3",
}
FBANK_FLOATS = 998 * 80
FBANK_BYTES = FBANK_FLOATS * 4
CALIBRATION_NAME = re.compile(r"cal_(\d+)\.f32")


class QuantizationInputError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def calibration_files(directory: Path) -> list[Path]:
    indexed: list[tuple[int, Path]] = []
    for path in directory.glob("cal_*.f32"):
        match = CALIBRATION_NAME.fullmatch(path.name)
        if match is not None:
            indexed.append((int(match.group(1)), path))
    indexed.sort(key=lambda item: item[0])
    paths = [item[1] for item in indexed]
    if len(paths) != EXPECTED_CALIBRATION_WINDOWS:
        raise QuantizationInputError(
            f"expected {EXPECTED_CALIBRATION_WINDOWS} calibration windows, found {len(paths)}"
        )
    if [item[0] for item in indexed] != list(range(EXPECTED_CALIBRATION_WINDOWS)):
        raise QuantizationInputError("calibration windows must be consecutively named cal_0..cal_20")
    for path in paths:
        if path.stat().st_size != FBANK_BYTES:
            raise QuantizationInputError(
                f"invalid calibration tensor size for {path.name}: {path.stat().st_size}"
            )
    return paths


def calibration_digest(paths: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def verify_versions() -> None:
    for package, expected in EXPECTED_VERSIONS.items():
        actual = importlib.metadata.version(package)
        if actual != expected:
            raise QuantizationInputError(f"{package} must be {expected}, found {actual}")


def quantize(source: Path, calibration_dir: Path, output: Path) -> dict[str, object]:
    if not source.is_file():
        raise QuantizationInputError(f"missing FP32 encoder: {source}")
    source_sha256 = sha256_file(source)
    if source_sha256 != EXPECTED_SOURCE_SHA256:
        raise QuantizationInputError(f"unexpected FP32 encoder sha256: {source_sha256}")
    paths = calibration_files(calibration_dir)
    digest = calibration_digest(paths)
    if digest != EXPECTED_CALIBRATION_DIGEST:
        raise QuantizationInputError(f"unexpected calibration digest: {digest}")
    verify_versions()

    import numpy as np
    from onnxruntime.quantization import (
        CalibrationDataReader,
        QuantFormat,
        QuantType,
        quantize_static,
    )

    samples = [np.fromfile(path, dtype=np.float32).reshape(1, 998, 80) for path in paths]

    class Reader(CalibrationDataReader):
        def __init__(self) -> None:
            self.index = 0

        def get_next(self) -> dict[str, object] | None:
            if self.index >= len(samples):
                return None
            item = {"fbank": samples[self.index]}
            self.index += 1
            return item

        def rewind(self) -> None:
            self.index = 0

    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        raise QuantizationInputError(f"refusing to overwrite existing output: {output}")
    with tempfile.TemporaryDirectory(prefix="community-encoder-", dir=output.parent) as directory:
        candidate = Path(directory) / output.name
        quantize_static(
            str(source),
            str(candidate),
            Reader(),
            quant_format=QuantFormat.QDQ,
            per_channel=True,
            weight_type=QuantType.QInt8,
            activation_type=QuantType.QUInt8,
        )
        candidate_sha256 = sha256_file(candidate)
        if candidate.stat().st_size != EXPECTED_OUTPUT_BYTES:
            raise QuantizationInputError(
                f"unexpected quantized encoder size: {candidate.stat().st_size}"
            )
        if candidate_sha256 != EXPECTED_OUTPUT_SHA256:
            raise QuantizationInputError(
                f"unexpected quantized encoder sha256: {candidate_sha256}"
            )
        candidate.replace(output)

    provenance: dict[str, object] = {
        "source": {"file": source.name, "sha256": source_sha256},
        "calibration": {"windows": len(paths), "digest": digest},
        "quantization": {
            "format": "QDQ",
            "perChannel": True,
            "weightType": "QInt8",
            "activationType": "QUInt8",
        },
        "dependencies": EXPECTED_VERSIONS,
        "output": {
            "file": output.name,
            "sizeBytes": output.stat().st_size,
            "sha256": sha256_file(output),
        },
    }
    output.with_suffix(output.suffix + ".provenance.json").write_text(
        json.dumps(provenance, indent=2) + "\n", encoding="utf-8"
    )
    return provenance


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--calibration-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(quantize(args.source, args.calibration_dir, args.output), indent=2))


if __name__ == "__main__":
    main()
