export {
  TextToSpeechSdk,
  TtsErrorCode,
  TextToSpeechException,
  RunMode,
  PlayType,
  QueueMode,
  CompleteType,
  StopType,
  LicenseInfo,
  LicenseActivationResult
} from './src/main/ets/TextToSpeechApi';

export type {
  Callback,
  LicenseActivationCallback,
  TextToSpeechEngine,
  SpeakListener,
  CreateEngineParams,
  VoiceQuery,
  VoiceInfo,
  SpeakParams,
  StartResponse,
  SynthesisResponse,
  CompleteResponse,
  StopResponse
} from './src/main/ets/TextToSpeechApi';
